CREATE TABLE dbo.`races` (
  `RaceID` smallint NOT NULL AUTO_INCREMENT,
  `Date` date DEFAULT NULL,
  `IsRoad` bit(1) NOT NULL,
  `IsCrossCountry` bit(1) NOT NULL,
  `Number` tinyint NOT NULL,
  `Name` varchar(50) NOT NULL,
  `CityID` smallint NOT NULL,
  `Distance` decimal(12,9) NOT NULL,
  `IsOutOfSeries` bit(1) NOT NULL,
  `IsCancelled` bit(1) NOT NULL,
  `IsMissing` bit(1) NOT NULL,
  `Link` char(33) DEFAULT NULL,
  `Year` smallint NOT NULL,
  `UrlName` varchar(50) GENERATED ALWAYS AS (replace(replace(replace(replace(replace(replace(replace(replace(lower(`Name`),_latin1'&',_utf8mb4''),_latin1'.',_utf8mb4'_'),_latin1' ',_utf8mb4'_'),_latin1'\'',_utf8mb4''),_latin1'1/2',_utf8mb4'half'),_latin1'-',_utf8mb4'_'),_latin1'/',_utf8mb4'_'),_latin1'\\',_utf8mb4'_')) VIRTUAL NOT NULL,
  `ShortName` varchar(50) DEFAULT NULL,
  `DistanceID` tinyint DEFAULT NULL,
  `IsMiles` bit(1) NOT NULL,
  `IsCertified` bit(1) DEFAULT NULL,
  `SeriesID` tinyint DEFAULT NULL,
  `IsAwardEligible` bit(1) DEFAULT NULL,
  PRIMARY KEY (`RaceID`),
  UNIQUE KEY `idx_year_urlname` (`Year`,`UrlName`),
  KEY `fk_races_cityid` (`CityID`),
  CONSTRAINT `fk_races_cityid` FOREIGN KEY (`CityID`) REFERENCES `cities` (`CityID`)
) ENGINE=InnoDB AUTO_INCREMENT=607 DEFAULT CHARSET=latin1